blank_issues_enabled: true
contact_links:
  - name: Community support
    url: https://github.com/gfmio/awesome-github-template
    about: Please ask and answer questions here.
  - name: Security vulnerabilities
    url: https://example.td
    about: Please report security vulnerabilities here.
