blank_issues_enabled: false
contact_links:
  - name: Security vulnerabilities
    url: mailto:security@example.tld
    about: Please send a PGP-encrypted email to security@example.tld with the PGP key at https://example.tld/pgp.
