blank_issues_enabled: true
contact_links:
  - name: Community support
    url: https://github.com/gfmio/awesome-github-template/issues
    about: Please ask and answer questions here (using a blank template).
  - name: Security vulnerabilities
    url: https://example.tld
    about: Please report security vulnerabilities here.
